apiVersion: v1      #manifest used for deployment of single sservice
kind: Service
metadata:
  name: docker-c6assignment-service
  namespace: wilp-c6assignment
spec:
  selector:
    app: docker-c6assignment-service-app
  ports:
    - name: weborder
      port: 35351
      targetPort: 8081
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-ac6assignment-service-app
  namespace: wilp-c6assignment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-ac6assignment-service-app
  template:
    metadata:
      labels:
        app: docker-ac6assignment-service-app
    spec:
      containers:
        - name: docker-ac6assignment-service-weborder
          image: survin00/weborder:1.0.0
          ports:
            - containerPort: 8081
          resources:
            limits:
              cpu: "2"
              memory: "1024Mi"
            requests:
              cpu: "0.01"
              memory: "2Mi"