apiVersion: v1
kind: Service
metadata:
  name: docker-c6assignment-service
  namespace: wilp-c6assignment
spec:
  selector:
    app: docker-c6assignment-service-app
  ports:
    - port: 35351
      targetPort: 2300
  type: LoadBalancer